### PR TITLE
feat: hello-world-app in ExpressJS

### LINKED ISSUE #1: Add more frameworks
Make sure you read the README and follow all the guidelines. Please create/fill up the necessary readme files inside the framework folders.

### PR DESCRIPTION
**Pull request by gitaalekhyapaul**
# Description
- hello-world-app in ExpressJS

Fixes #1

### CODE REVIEW

**Comment by gitaalekhyapaul** [comment]
Hey, @diptangsu I will be working on Both ExpressJS in Javascript and Typescript for your repo!
It would be great if you could assign me to #1

**Comment by gitaalekhyapaul** [comment]
@diptangsu Have you reviewed the PR? If you have any issues, kindly do let me know!

**Comment by diptangsu** [comment]
@gitaalekhyapaul Can you pull once and update the README to fix the merge conflict? Just add your text at the end of whatever is already there

**Comment by gitaalekhyapaul** [comment]
Sure! @diptangsu

**Comment by gitaalekhyapaul** [comment]
@diptangsu Here you go!

**Comment by gitaalekhyapaul** [comment]
@diptangsu I have fix merge conflicts and updated the README as per your liking!

**Comment by gitaalekhyapaul** [comment]
@diptangsu  as per the new Hacktober rules:
https://hacktoberfest.digitalocean.com/hacktoberfest-update
Please do the following:
1. add a **'hacktober'** topic to your repository 
2. Kindly add a **'hacktoberfest-accepted'** label to this accepted PR

**Pull request merged**
